apiVersion: apps/v1
kind: Deployment
metadata:
  name: doug-translate-deloyment
spec:
  selector:
    matchLabels:
      app: doug-translate
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: doug-translate
    spec:
      containers:
        - name: frontend
          image: defenseunicorns/doug-translate:latest
          ports:
            - containerPort: 3000
          env:
            - name: LEAPFROGAI_BASE_URL
              value: "###ZARF_VAR_LEAPFROGAI_BASE_URL###"
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "1000m"
