apiVersion: apps/v1
kind: Deployment
metadata:
  name: doug-translate
spec:
  selector:
    matchLabels:
      app: doug-translate
  replicas: 1
  template:
    metadata:
      labels:
        app: doug-translate
    spec:
      containers:
        - name: doug-translate
          image: defenseunicorns/doug-translate:0.0.1
          ports:
            - containerPort: 3000
          env:
            - name: LEAPFROGAI_BASE_URL
              value: "###ZARF_VAR_LEAPFROGAI_BASE_URL###"
            - name: ORIGIN
              value: "https://###ZARF_VAR_DOMAIN###"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "1000m"
