apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: doug-translate
spec:
  gateways:
    - istio-system/tenant
  hosts:
    - "doug-translate.###ZARF_VAR_DOMAIN###"
  http:
    - route:
        - destination:
            host: doug-translate.doug-translate.svc.cluster.local
            port:
              number: 3000
