name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js 20
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run check
      - run: npm run lint

  setup-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup K3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - run: ./hack/cluster-up.sh
      - name: Setup Zarf
        uses: defenseunicorns/setup-zarf@v1.0.0
        with:
          download-init-package: true
      - name: Zarf Init
        run: zarf init --confirm -l=trace
      - name: Deploy Dos-Games
        run: zarf package deploy oci://🦄/dos-games:1.0.0-amd64 --confirm -l=trace --oci-concurrency=5 --key https://zarf.dev/cosign.pub
      - name: List Packages
        run: zarf package list
      - name: Use Node.js 20
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20
          cache: npm
      - run: ./hack/build.sh
      - run: ./hack/deploy-amd64.sh "leapfrog.du.dev" "du.dev" "ctransformers" # dummy env vars
      - run: zarf package inspect doug-translate
